#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "NeoSolarized"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_iseparator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = false
    enable_statusline_mode = false
    statusline_unicode_symbols = false
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true
    # filemanager
    filemanager = "nerdtree"
    filetree_direction = "left"
    enable_vimfiler_gitstatus = true

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "cycle"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = 'lang#go'

[[layers]]
  name = "format"

[[layers]]
  name = "japanese"

[[layers]]
  name = "fzf"

[[layers]]
  name = "lang#rust"

[[layers]]
  name = "lsp"
  filetypes = [
    "rust"
  ]
  [layers.override_cmd]
    rust = ["rls"]

[[layers]]
  name = 'lang#c'
  format_on_save = true
  enable_clang_syntax_highlight = true
  clang_executable = "/usr/bin/clang"
  clang_flag = ['-std=c++20','-stdlib=libc++','-O2','-Wall','-DNDEBUG']
  [layer.clang_std]
    c = "c17"
    cpp = "c20"

[[layers]]
  name = "checkers"

[[layers]]
  name = 'lang#python'
  python_interpreter = '/usr/bin/python3.9'
  python_file_head = [
    '#!/usr/bin/env python',
    '# -*- coding: utf-8 -*-',
    '',
    ''
  ]

[[layers]]
  name = 'git'

[[layers]]
  name = "github"

[[layers]]
  name = 'VersionControl'

[[layers]]
  name = "denite"

[[layers]]
  name = 'lang#nim'

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "ui"
  enable = true
  enable_sidebar = true

[[layers]]
  name = "tools"

[[layers]]
  name = "lang#dockerfile"

[[custom_plugins]]
  repo = 'https://github.com/tpope/vim-fugitive'
  merged = false

[[custom_plugins]]
  repo = 'https://github.com/airblade/vim-gitgutter'
  merged = false

[[custom_plugins]]
  repo = 'https://github.com/ryanoasis/vim-devicons'
  merged = false

[[custom_plugins]]
  repo = 'https://github.com/tpope/vim-commentary'
  merged = false

[[custom_plugins]]
  repo = 'https://github.com/tpope/vim-repeat'
  merged = false

[[custom_plugins]]
  repo = 'SirVer/ultisnips'
  #hook_add = '''
  #let g:UltiSnipsSnippetDirectories=[$HOME.'/.vim-snippets/UltiSnips', 'UltiSnips']
  #" snippet 次へ
  #let g:UltiSnipsJumpForwardTrigger="<tab>"
  #" snippet 前へ
  #let g:UltiSnipsJumpBackwardTrigger="<s-tab>"
  #'''
  merged = false

[[custom_plugins]]
  repo = 'https://github.com/sheerun/vim-polyglot'
  merged = false

[[custom_plugins]]
  repo = 'https://github.com/itchyny/lightline.vim'
  merged = false
